[".config/tmux/plugins/tpm"]
type = "git-repo"
url = "https://github.com/tmux-plugins/tpm.git"
refreshPeriod = "168h"
clone.args = ["--depth", "1"]
pull.args = ["--ff-only"]

[".config/nvim"]
type = "git-repo"
url = "https://github.com/LazyVim/starter"
refreshPeriod = "24h"
clone.args = ["--depth", "1", "-b", "main"]
